autofetch_sources: true
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - smartcontractkit/chainlink@1.2.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
      - "@chainlink=smartcontractkit/chainlink@1.2.1"
